/**
 * 删除看板
 */
exports.response = function (req, res) {
  return {
    code: '0',
    msg: 'OK',
    resultData: {
        "postnTree": [
             {
                "id":"1-461BJOK",
                "rowId":"1-3NEO5LJ",
                "login":"0005313323",
                "loginName":"1-3NEO5LJ",
                "postnId":"1-461BL77",
                "postnName":"631ad53f-fa79-4dbf-ada9-d775cc33d68b",
                "isMainPostn":false,
                "orgId":"ZZ001041107013",
                "orgName":"上海武定路证券营业部",
                "upPostnId":"1-461BL3W",
                "upPostnName":"财富中心绩效管理岗",
                "postnTypeCD":"4",
                "xCfzxFlg":"jxst",
                "postnDesc":"1-3NEO5LJ团队",
                "children":null,
                "teamCount":3,
                "empCount":null,
            },
            {
                "id":"1-461BL5F",
                "rowId":"1-2SQPT23",
                "login":"0008298991",
                "loginName":"1-2SQPT23",
                "postnId":"1-461BL55",
                "postnName":"8fb45a1d-3c90-4226-b287-5f8fd6ec19eb",
                "isMainPostn":false,
                "orgId":"ZZ001041063",
                "orgName":"常州和平北路证券营业部",
                "upPostnId":"1-461BL3W",
                "upPostnName":"财富中心绩效管理岗",
                "postnTypeCD":"4",
                "xCfzxFlg":"jxst",
                "postnDesc":"1-2SQPT23团队",
                "children":null,
                "teamCount":3,
                "empCount":null,
            },
            {
                "id":"1-461BL5L",
                "rowId":"1-P66E",
                "login":"001189",
                "loginName":"1-P66E",
                "postnId":"1-461BL7F",
                "postnName":"35f52675-ba69-4734-9f6f-b608ee56d567",
                "isMainPostn":false,
                "orgId":"ZZ001041058",
                "orgName":"苏州人民路证券营业部",
                "upPostnId":"1-461BL3W",
                "upPostnName":"财富中心绩效管理岗",
                "postnTypeCD":"4",
                "xCfzxFlg":"jxst",
                "postnDesc":"1-P66E团队",
                "children":null,
                "teamCount":3,
                "empCount":null,
            },
        ],
        "currentPostn": {
            "id":"1-461BJOG",
            "rowId":"1-OCEN",
            "login":"001188",
            "loginName":"1-OCEN",
            "postnId":"1-461BL3W",
            "postnName":"财富中心绩效管理岗",
            "isMainPostn":false,
            "orgId":"ZZ00104109301",
            "orgName":"财富中心1",
            "upPostnId":"1-460XFDL",
            "upPostnName":"分公司绩效管理岗",
            "postnTypeCD":"3",
            "xCfzxFlg":"jxst",
            "postnDesc":null,
            "children":null,
        },
    },
  };
};