/**
 * 查询创建看板的可见范围
 */

exports.response = function (req, res) {
  return {
    code: '0',
    msg: 'OK',
    resultData: {
      id: 'ZZ001041',
      name: '经纪及财富管理部',
      level: '1',
      pid: 'ZZ001',
      pname: '华泰证券股份有限公司',
      children: [
        {
          id: 'ZZ001041093',
          name: '南京分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ001041103',
          name: '苏州分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ001041106',
          name: '南通分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ001041107',
          name: '上海分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ001041108',
          name: '北京分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ001041109',
          name: '天津分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ001041111',
          name: '湖北分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ001041112',
          name: '广东分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ001041116',
          name: '辽宁分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ001041118',
          name: '浙江分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ001041120',
          name: '四川分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ001041151',
          name: '黑龙江分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ001041166',
          name: '深圳分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ323261',
          name: '常州分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ323262',
          name: '徐州分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ323263',
          name: '无锡分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ323264',
          name: '河南分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ323265',
          name: '福建分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ323266',
          name: '扬州分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ323267',
          name: '安徽分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ323268',
          name: '山东分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ323269',
          name: '淮安分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ323270',
          name: '盐城分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ323271',
          name: '泰州分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ323272',
          name: '镇江分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ323273',
          name: '江阴分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ323274',
          name: '湖南分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ323275',
          name: '云南分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ323288',
          name: '江西分公司',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
        {
          id: 'ZZ323289',
          name: '西北分公司（筹）',
          level: '2',
          pid: 'ZZ001041',
          pname: '经纪及财富管理部',
          children: null,
        },
      ],
    },
  };
};
