/**
 * 查询当前用户可以编辑的报表看板
 */

exports.response = function (req, res) {
  return {
    code: '0',
    msg: 'OK',
    resultData: [
      {
        id: 1273,
        name: '12',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'RELEASE',
        createTime: '2017-08-14 14:51:50',
        updateTime: '2017-08-16 09:26:20',
        pubTime: '2017-08-16 09:26:20',
        isEditable: 'Y',
        isPublishable: 'Y',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 1275,
        name: 'uat-经营1',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'RELEASE',
        createTime: '2017-08-14 14:59:53',
        updateTime: '2017-08-14 15:00:50',
        pubTime: '2017-08-14 15:00:50',
        isEditable: 'Y',
        isPublishable: 'Y',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
          {
            id: 'ZZ323270',
            name: '盐城分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323274',
            name: '湖南分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041106',
            name: '南通分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041120',
            name: '四川分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041107',
            name: '上海分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041109',
            name: '天津分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041116',
            name: '辽宁分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323264',
            name: '河南分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323268',
            name: '山东分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323273',
            name: '江阴分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041112',
            name: '广东分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041166',
            name: '深圳分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323262',
            name: '徐州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323263',
            name: '无锡分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323265',
            name: '福建分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041151',
            name: '黑龙江分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323267',
            name: '安徽分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323289',
            name: '西北分公司（筹）',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041108',
            name: '北京分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323275',
            name: '云南分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041111',
            name: '湖北分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041118',
            name: '浙江分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041093',
            name: '南京分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323269',
            name: '淮安分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323271',
            name: '泰州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323288',
            name: '江西分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041103',
            name: '苏州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323261',
            name: '常州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323266',
            name: '扬州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323272',
            name: '镇江分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
        ],
      },
      {
        id: 1274,
        name: '13',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-14 14:52:59',
        updateTime: '2017-08-14 14:52:59',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 1271,
        name: 'uat-投顾11',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'RELEASE',
        createTime: '2017-08-14 14:34:52',
        updateTime: '2017-08-14 14:46:26',
        pubTime: '2017-08-14 14:46:26',
        isEditable: 'Y',
        isPublishable: 'Y',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
          {
            id: 'ZZ001041093',
            name: '南京分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
        ],
      },
      {
        id: 1202,
        name: 'wsd111',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'RELEASE',
        createTime: '2017-08-11 14:18:31',
        updateTime: '2017-08-14 14:41:49',
        pubTime: '2017-08-14 14:41:49',
        isEditable: 'Y',
        isPublishable: 'Y',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
          {
            id: 'ZZ001041120',
            name: '四川分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323270',
            name: '盐城分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323274',
            name: '湖南分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041106',
            name: '南通分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041107',
            name: '上海分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041109',
            name: '天津分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041116',
            name: '辽宁分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323264',
            name: '河南分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323268',
            name: '山东分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323273',
            name: '江阴分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041112',
            name: '广东分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041166',
            name: '深圳分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323262',
            name: '徐州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323263',
            name: '无锡分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323265',
            name: '福建分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041151',
            name: '黑龙江分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323267',
            name: '安徽分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323289',
            name: '西北分公司（筹）',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041108',
            name: '北京分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323275',
            name: '云南分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041093',
            name: '南京分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041111',
            name: '湖北分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041118',
            name: '浙江分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323269',
            name: '淮安分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323271',
            name: '泰州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323288',
            name: '江西分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041103',
            name: '苏州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323261',
            name: '常州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323266',
            name: '扬州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323272',
            name: '镇江分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
        ],
      },
      {
        id: 1270,
        name: 'uat-投顾1',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-14 14:26:39',
        updateTime: '2017-08-14 14:26:39',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 1231,
        name: 'wew2',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'RELEASE',
        createTime: '2017-08-11 17:43:14',
        updateTime: '2017-08-11 17:43:35',
        pubTime: '2017-08-11 17:43:35',
        isEditable: 'Y',
        isPublishable: 'Y',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 1230,
        name: 'wew',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-11 17:42:43',
        updateTime: '2017-08-11 17:42:43',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 1214,
        name: 'test11',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'RELEASE',
        createTime: '2017-08-11 15:33:00',
        updateTime: '2017-08-11 15:36:35',
        pubTime: '2017-08-11 15:36:35',
        isEditable: 'Y',
        isPublishable: 'Y',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 1197,
        name: '1122',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-11 11:26:10',
        updateTime: '2017-08-11 11:26:10',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 1196,
        name: '11',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-11 11:26:06',
        updateTime: '2017-08-11 11:26:06',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 1162,
        name: 'test33',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-10 14:23:21',
        updateTime: '2017-08-10 14:23:21',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 1161,
        name: 'test22',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-10 14:23:04',
        updateTime: '2017-08-10 14:23:04',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 914,
        name: '6666',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-02 13:27:40',
        updateTime: '2017-08-07 17:29:48',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'Y',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 1051,
        name: '121',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'RELEASE',
        createTime: '2017-08-07 14:23:01',
        updateTime: '2017-08-07 14:26:11',
        pubTime: '2017-08-07 14:26:11',
        isEditable: 'Y',
        isPublishable: 'Y',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 1030,
        name: '123',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-04 15:27:12',
        updateTime: '2017-08-07 14:25:47',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'Y',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
          {
            id: 'ZZ001041106',
            name: '南通分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041120',
            name: '四川分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323270',
            name: '盐城分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323274',
            name: '湖南分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041107',
            name: '上海分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041109',
            name: '天津分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041116',
            name: '辽宁分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323264',
            name: '河南分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323268',
            name: '山东分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323273',
            name: '江阴分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041112',
            name: '广东分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041166',
            name: '深圳分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323262',
            name: '徐州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323263',
            name: '无锡分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323265',
            name: '福建分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041151',
            name: '黑龙江分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323267',
            name: '安徽分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323289',
            name: '西北分公司（筹）',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041108',
            name: '北京分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323275',
            name: '云南分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041093',
            name: '南京分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041111',
            name: '湖北分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041118',
            name: '浙江分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323269',
            name: '淮安分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323271',
            name: '泰州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323288',
            name: '江西分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041103',
            name: '苏州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323261',
            name: '常州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323266',
            name: '扬州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323272',
            name: '镇江分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
        ],
      },
      {
        id: 1011,
        name: '123',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-04 09:03:23',
        updateTime: '2017-08-04 09:03:23',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 1010,
        name: '312',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-03 18:14:13',
        updateTime: '2017-08-03 18:14:13',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 976,
        name: '都是',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-03 11:12:27',
        updateTime: '2017-08-03 11:12:40',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'Y',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 975,
        name: '123',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-03 11:01:12',
        updateTime: '2017-08-03 11:01:12',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 974,
        name: '123',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-03 10:06:22',
        updateTime: '2017-08-03 10:06:22',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 973,
        name: '123',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-03 10:05:49',
        updateTime: '2017-08-03 10:05:49',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 972,
        name: '第三个',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-03 09:45:36',
        updateTime: '2017-08-03 09:45:36',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 971,
        name: '而发热',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-03 09:44:36',
        updateTime: '2017-08-03 09:44:36',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 970,
        name: '4645',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-03 09:13:33',
        updateTime: '2017-08-03 09:13:55',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'Y',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 957,
        name: '1234456',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-02 17:27:20',
        updateTime: '2017-08-02 17:27:20',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 956,
        name: '123',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-02 17:09:10',
        updateTime: '2017-08-02 17:09:10',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 955,
        name: '123',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-02 17:04:26',
        updateTime: '2017-08-02 17:04:26',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 954,
        name: '123',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-02 17:03:38',
        updateTime: '2017-08-02 17:03:38',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 953,
        name: '789',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-02 16:59:34',
        updateTime: '2017-08-02 16:59:34',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 952,
        name: '789',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-02 16:14:21',
        updateTime: '2017-08-02 16:14:21',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 951,
        name: '456',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-02 16:13:46',
        updateTime: '2017-08-02 16:13:46',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 950,
        name: '123456',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-02 16:08:33',
        updateTime: '2017-08-02 16:08:33',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 932,
        name: '445',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-02 14:45:47',
        updateTime: '2017-08-02 14:45:47',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 931,
        name: '123',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-02 14:43:56',
        updateTime: '2017-08-02 14:43:56',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 930,
        name: '123',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-02 14:27:36',
        updateTime: '2017-08-02 14:27:36',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 915,
        name: '是多少',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-02 13:57:35',
        updateTime: '2017-08-02 13:57:35',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'N',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 913,
        name: '44444',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-02 10:59:00',
        updateTime: '2017-08-02 10:59:53',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'Y',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 912,
        name: '22222',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-02 10:53:30',
        updateTime: '2017-08-02 10:54:04',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'Y',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 911,
        name: '111111',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-02 10:43:18',
        updateTime: '2017-08-02 10:44:39',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'Y',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 910,
        name: '111111',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-02 10:39:06',
        updateTime: '2017-08-02 10:42:06',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'Y',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 870,
        name: '123',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '未发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'UNRELEASE',
        createTime: '2017-08-01 14:59:04',
        updateTime: '2017-08-01 14:59:29',
        pubTime: null,
        isEditable: 'Y',
        isPublishable: 'Y',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
        ],
      },
      {
        id: 850,
        name: '0801-01',
        boardType: 'TYPE_TGJX',
        boardTypeDesc: '投顾绩效',
        boardStatusDesc: '发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'RELEASE',
        createTime: '2017-08-01 09:45:45',
        updateTime: '2017-08-01 10:06:23',
        pubTime: '2017-08-01 10:06:23',
        isEditable: 'Y',
        isPublishable: 'Y',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
          {
            id: 'ZZ001041120',
            name: '四川分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323274',
            name: '湖南分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041106',
            name: '南通分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041109',
            name: '天津分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323268',
            name: '山东分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323273',
            name: '江阴分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041166',
            name: '深圳分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323262',
            name: '徐州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323267',
            name: '安徽分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041108',
            name: '北京分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323275',
            name: '云南分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041118',
            name: '浙江分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323288',
            name: '江西分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041093',
            name: '南京分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323261',
            name: '常州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323266',
            name: '扬州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323272',
            name: '镇江分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041103',
            name: '苏州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
        ],
      },
      {
        id: 790,
        name: '测试经营指标',
        boardType: 'TYPE_JYYJ',
        boardTypeDesc: '经营业绩',
        boardStatusDesc: '发布',
        description: null,
        ownerOrgId: 'ZZ001041',
        boardStatus: 'RELEASE',
        createTime: '2017-07-28 14:20:16',
        updateTime: '2017-07-28 17:29:01',
        pubTime: '2017-07-28 17:29:01',
        isEditable: 'Y',
        isPublishable: 'Y',
        orgModel: [
          {
            id: 'ZZ001041',
            name: '经纪及财富管理部',
            level: '1',
            pid: 'ZZ001',
            pname: '华泰证券股份有限公司',
            children: null,
          },
          {
            id: 'ZZ001041106',
            name: '南通分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041107',
            name: '上海分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041116',
            name: '辽宁分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041112',
            name: '广东分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323262',
            name: '徐州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041111',
            name: '湖北分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041093',
            name: '南京分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ001041103',
            name: '苏州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
          {
            id: 'ZZ323261',
            name: '常州分公司',
            level: '2',
            pid: 'ZZ001041',
            pname: '经纪及财富管理部',
            children: null,
          },
        ],
      },
    ],
  };
};
