/**
 * 查询用户的可见报表看板的信息
 */

exports.response = function (req, res) {
  return {
    code: '0',
    msg: 'OK',
    resultData: {
      ordinary: [
        {
          id: 1273,
          name: '12',
          boardType: 'TYPE_TGJX',
          boardTypeDesc: '投顾绩效',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-14 14:51:50',
          updateTime: '2017-08-16 09:26:20',
          pubTime: '2017-08-16 09:26:20',
          isEditable: 'Y',
          summuryIndicators: 'hignCustInfoCompletePercent,currSignCustAset',
          detailIndicators: null,
          coreIndicators: null,
          custContrastIndicators: null,
          investContrastIndicators: null,
        },
        {
          id: 1275,
          name: 'uat-经营1',
          boardType: 'TYPE_JYYJ',
          boardTypeDesc: '经营业绩',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-14 14:59:53',
          updateTime: '2017-08-14 15:00:50',
          pubTime: '2017-08-14 15:00:50',
          isEditable: 'Y',
          summuryIndicators: 'effCustNum,InminorCustNum,newCustNum,oNewCustNum,oNewPrdtCustNum,pNewCustNum',
          detailIndicators: 'custAmountDetail:InminorCustNum;newCustNum',
          coreIndicators: null,
          custContrastIndicators: null,
          investContrastIndicators: null,
        },
        {
          id: 1271,
          name: 'uat-投顾11',
          boardType: 'TYPE_TGJX',
          boardTypeDesc: '投顾绩效',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-14 14:34:52',
          updateTime: '2017-08-14 14:46:26',
          pubTime: '2017-08-14 14:46:26',
          isEditable: 'Y',
          summuryIndicators: 'hignCustInfoCompletePercent,platformSignAvgAmt,signCustPercent,effSignCustNum,prdtTranAmt,configReportNum,tgInNum,netIncome',
          detailIndicators: 'performanceIndicator:gjTranAmt;purRake;tgNum;signCustPercent;signPurPercent;prdtTranAmt;configReportNum;purInteIncome',
          coreIndicators: null,
          custContrastIndicators: null,
          investContrastIndicators: null,
        },
        {
          id: 1202,
          name: 'wsd111',
          boardType: 'TYPE_TGJX',
          boardTypeDesc: '投顾绩效',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 14:18:31',
          updateTime: '2017-08-14 14:41:49',
          pubTime: '2017-08-14 14:41:49',
          isEditable: 'Y',
          summuryIndicators: 'hignCustInfoCompletePercent,gjTranAmt',
          detailIndicators: null,
          coreIndicators: null,
          custContrastIndicators: null,
          investContrastIndicators: null,
        },
        {
          id: 1231,
          name: 'wew2',
          boardType: 'TYPE_JYYJ',
          boardTypeDesc: '经营业绩',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 17:43:14',
          updateTime: '2017-08-11 17:43:35',
          pubTime: '2017-08-11 17:43:35',
          isEditable: 'Y',
          summuryIndicators: 'allTotAset',
          detailIndicators: 'asetDetail:allTotAset',
          coreIndicators: null,
          custContrastIndicators: null,
          investContrastIndicators: null,
        },
        {
          id: 1214,
          name: 'test11',
          boardType: 'TYPE_JYYJ',
          boardTypeDesc: '经营业绩',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 15:33:00',
          updateTime: '2017-08-11 15:36:35',
          pubTime: '2017-08-11 15:36:35',
          isEditable: 'Y',
          summuryIndicators: 'curPrdtTranAmt,smTranAmt,otcTranAmt,taTranAmt,kfTranAmt',
          detailIndicators: 'asetDetail:allTotAset,productDetail:curPrdtTranAmt',
          coreIndicators: null,
          custContrastIndicators: null,
          investContrastIndicators: null,
        },
        {
          id: 1051,
          name: '121',
          boardType: 'TYPE_TGJX',
          boardTypeDesc: '投顾绩效',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-07 14:23:01',
          updateTime: '2017-08-07 14:26:11',
          pubTime: '2017-08-07 14:26:11',
          isEditable: 'Y',
          summuryIndicators: 'hignCustInfoCompletePercent,gjTranAmt',
          detailIndicators: 'performanceIndicator:signCustPercent;signPurPercent;custNum',
          coreIndicators: null,
          custContrastIndicators: null,
          investContrastIndicators: null,
        },
        {
          id: 850,
          name: '0801-01',
          boardType: 'TYPE_TGJX',
          boardTypeDesc: '投顾绩效',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-01 09:45:45',
          updateTime: '2017-08-01 10:06:23',
          pubTime: '2017-08-01 10:06:23',
          isEditable: 'Y',
          summuryIndicators: 'hignCustInfoCompletePercent,gjTranAmt,platformSignAvgAmt,signCustPercent,signPurPercent,effSignCustNum,accountFee,newCustInAset,configReportNum,configRiskNum,platformUsedPercent,netIncome,tgInNum,currSignCustAset,purRake,infoCompPercent',
          detailIndicators: 'performanceIndicator:gjTranAmt;tgNum;custNum;signCustPercent;currSignCustNum;currSignCustAset;platformSignAvgAmt;purRake;hignCustInfoCompletePercent;configReportNum;signPurPercent;effSignCustNum;accountFee;platformUsedPercent;totAset;prdtPurFee;purInteIncome;riskPreferEffRate;netIncome;prdtTranAmt',
          coreIndicators: null,
          custContrastIndicators: null,
          investContrastIndicators: null,
        },
        {
          id: 790,
          name: '测试经营指标',
          boardType: 'TYPE_JYYJ',
          boardTypeDesc: '经营业绩',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-07-28 14:20:16',
          updateTime: '2017-07-28 17:29:01',
          pubTime: '2017-07-28 17:29:01',
          isEditable: 'Y',
          summuryIndicators: 'InminorCustNum,newCustNum,pNewCustNum,oNewCustNum,oNewPrdtCustNum,totCustNum,pCustNum,oCustNum,oNoPrdtCustNum,pCustAset,cirMktVal,mktFb,mktZq,fundMktVal,allTotAsetDis,debVal,tradTranAmt,dbGjTranAmt,hskhTranAmt,minorCustNum,oNoPrdtCustAset,oPrdtCustAset,gjzCustAset,finaMktVal,priFundMktVal,otcMktVal,optMktVal,avgBal,purFinAmt,new_cust_aset,bal,mktLmt,ttfMktVal,mktVal,cirMktValCopy,allTotAset,zhTranAmt,kfHbTranAmt,kfZqTranAmt,tradTranAmtCopy,threeTranAmt,newThreeTranAmt,oldThreeTranAmt,tranAmtOpt,curPrdtTranAmt,kfTranAmt,taTranAmt,otcTranAmt,smTranAmt,nowMktVal,nowFundMktVal,nowFinaMktVal,nowOtcMktVal,nowPriFundMktVal,avgMktVal,avgFundMktVal,avgFinaMktVal,avgOtcMktVal,avgPriFundMktVal,nowTtfMktVal,avgTtfMktVal,ljOpenBusi,rzrqBusi,ttfBusi,gpqqBusi,hgtBusi,sgtBusi,cybBusi,zlcftBusi,otcBusi,gpzyBusi,xsbBusi,dqOpenBusi,rzrqBusiCurr,gpzyBusiCurr,gpqqBusiCurr,ttfBusiCurr,otcBusiCurr,cybBusiCurr',
          detailIndicators: 'custAmountDetail:InminorCustNum;newCustNum;totCustNum;pCustNum;oCustNum;effCustNum;minorCustNum,asetDetail:oNoPrdtCustAset;gjzCustAset;new_cust_aset;allTotAsetDis;allTotAset;pCustAset;oPrdtCustAset;cirMktVal;mktZq;fundMktVal;finaMktVal;priFundMktVal;otcMktVal;optMktVal;avgBal;purFinAmt,transAmountDetail:zhTranAmt;tradTranAmt;hskhTranAmt;threeTranAmt;tranAmtOpt,productDetail:nowMktVal;avgMktVal;curPrdtTranAmt;nowTtfMktVal;avgTtfMktVal,newBusinessDetail:ljOpenBusi;dqOpenBusi,pureIncomeDetail:totTranInt,hignCustServiceDetail:gjzFeeConfigPercent;gjzServiceCompPercentOrgan;gjzMotCompleteNum;gjzConfigRiskNum;gjzConfigReportNum;gjzMotTotNum',
          coreIndicators: null,
          custContrastIndicators: null,
          investContrastIndicators: null,
        }
      ],
      history: [
        {
          id: 1310,
          name: '1234756',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-15 15:43:52',
          updateTime: '2017-08-15 17:27:39',
          pubTime: '2017-08-15 17:27:39',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,purInteIncome,currSignCustNum,netIncome,tgNum',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'tgNum,tgInNum',
        },
        {
          id: 1292,
          name: '222',
          boardType: 'TYPE_LSDB_JYYJ',
          boardTypeDesc: '经营业绩历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-15 13:43:50',
          updateTime: '2017-08-15 13:43:50',
          pubTime: '2017-08-15 13:43:50',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totCustNum,allTotAset,zhTranAmt,curPrdtTranAmt',
          custContrastIndicators: 'totCustNum,pCustNum,oCustNum,oNewCustNum,oNewPrdtCustNum,InminorCustNum',
          investContrastIndicators: 'custNum',
        },
        {
          id: 1291,
          name: '111',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-15 13:43:30',
          updateTime: '2017-08-15 13:43:30',
          pubTime: '2017-08-15 13:43:30',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,purInteIncome,currSignCustNum,netIncome',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'tgNum,tgInNum',
        },
        {
          id: 1290,
          name: 'CESHISHISHIS',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-15 13:31:33',
          updateTime: '2017-08-15 13:31:33',
          pubTime: '2017-08-15 13:31:33',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'currSignCustAset,gjAvgPercent,purRake,prdtPurFee,currSignCustNum,prdtTranAmt',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'tgNum,tgInNum',
        },
        {
          id: 1280,
          name: '经营11',
          boardType: 'TYPE_LSDB_JYYJ',
          boardTypeDesc: '经营业绩历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-14 16:06:39',
          updateTime: '2017-08-14 16:07:57',
          pubTime: '2017-08-14 16:07:57',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'shNpRate,szNpRate,shzNpRate,gjzMotCompletePercent,gjzCustInfoCompletePercent,gjzInfoCompPercent,gjzStockInfoCompPercent,gjzNewInfoCompPercent',
          custContrastIndicators: 'totCustNum,pCustNum,oCustNum,oNewCustNum,oNewPrdtCustNum,InminorCustNum',
          investContrastIndicators: 'totCustNum,pCustNum,oCustNum,oNewCustNum,oNewPrdtCustNum,InminorCustNum'
        },
        {
          id: 1217,
          name: '投顾11',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 15:51:44',
          updateTime: '2017-08-14 15:56:57',
          pubTime: '2017-08-14 15:56:57',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'hignCustInfoCompletePercent,signCustPercent,signPurPercent,gjAvgPercent,motCompletePercent,infoCompPercent,riskPreferEffRate',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1232,
          name: 'SSSSSSSSSSSS',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-14 09:27:03',
          updateTime: '2017-08-14 09:27:03',
          pubTime: '2017-08-14 09:27:03',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,gjAvgPercent,purRake,prdtPurFee,purInteIncome,netIncome,prdtTranAmt',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1216,
          name: '我的老家在东北松花江上',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 15:50:01',
          updateTime: '2017-08-11 15:50:01',
          pubTime: '2017-08-11 15:50:01',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'gjAvgPercent,purRake,prdtPurFee,currSignCustNum,netIncome,prdtTranAmt',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1213,
          name: '绩效1111',
          boardType: 'TYPE_LSDB_JYYJ',
          boardTypeDesc: '经营业绩历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 15:28:04',
          updateTime: '2017-08-11 15:28:04',
          pubTime: '2017-08-11 15:28:04',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totCustNum,allTotAset,zhTranAmt,curPrdtTranAmt',
          custContrastIndicators: 'totCustNum,pCustNum,oCustNum,oNewCustNum,oNewPrdtCustNum,InminorCustNum',
          investContrastIndicators: 'totCustNum,pCustNum,oCustNum,oNewCustNum,oNewPrdtCustNum,InminorCustNum',
        },
        {
          id: 1212,
          name: '投顾33',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 15:26:23',
          updateTime: '2017-08-11 15:26:23',
          pubTime: '2017-08-11 15:26:23',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,hignCustInfoCompletePercent,gjTranAmt,tgNum',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1179,
          name: '李定国测试看板',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: '李定国测试看板',
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 10:02:59',
          updateTime: '2017-08-11 14:42:50',
          pubTime: '2017-08-11 14:42:50',
          isEditable: 'Y',
          summuryIndicators: 'tgNum,tgInNum,custNum,totAset,gjAvgPercent',
          detailIndicators: 'custAmountDetail:effCustNum;InminorCustNum;newCustNum;hignLoseCustPercent,newBusinessDetail:rzrqBusi;ttfBusi;gqppBusi;hgtBusi;sgtBusi',
          coreIndicators: 'tgInNum',
          custContrastIndicators: 'custNum',
          investContrastIndicators: 'tgInNum',
        },
        {
          id: 1209,
          name: 'dddwodoaofdafa',
          boardType: 'TYPE_LSDB_JYYJ',
          boardTypeDesc: '经营业绩历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: '用来测试999',
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 14:41:56',
          updateTime: '2017-08-11 14:41:56',
          pubTime: '2017-08-11 14:41:56',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'tgInNum',
          custContrastIndicators: 'custNum',
          investContrastIndicators: 'tgInNum',
        },
        {
          id: 1208,
          name: 'test',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 14:41:49',
          updateTime: '2017-08-11 14:41:49',
          pubTime: '2017-08-11 14:41:49',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,purInteIncome,currSignCustNum,prdtTranAmt,netIncome',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1207,
          name: 'ddddddd',
          boardType: 'TYPE_LSDB_JYYJ',
          boardTypeDesc: '经营业绩历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: '用来测试999',
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 14:37:54',
          updateTime: '2017-08-11 14:37:54',
          pubTime: '2017-08-11 14:37:54',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'tgInNum',
          custContrastIndicators: 'custNum',
          investContrastIndicators: 'custNum',
        },
        {
          id: 1205,
          name: 'xixixiixix',
          boardType: 'TYPE_LSDB_JYYJ',
          boardTypeDesc: '经营业绩历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: '用来测试999',
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 14:33:59',
          updateTime: '2017-08-11 14:33:59',
          pubTime: '2017-08-11 14:33:59',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'tgInNum',
          custContrastIndicators: 'custNum',
          investContrastIndicators: 'custNum',
        },
        {
          id: 1203,
          name: '投顾111',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 14:25:02',
          updateTime: '2017-08-11 14:25:02',
          pubTime: '2017-08-11 14:25:02',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,purInteIncome,currSignCustNum,netIncome',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1200,
          name: '676767',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 11:37:26',
          updateTime: '2017-08-11 11:37:26',
          pubTime: '2017-08-11 11:37:26',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,currSignCustNum,gjTranAmt',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1199,
          name: '4444',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 11:27:31',
          updateTime: '2017-08-11 11:27:31',
          pubTime: '2017-08-11 11:27:31',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,currSignCustNum',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1195,
          name: '历史对比123',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 11:23:04',
          updateTime: '2017-08-11 11:23:04',
          pubTime: '2017-08-11 11:23:04',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,currSignCustNum,gjTranAmt',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1194,
          name: '787878',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 11:16:43',
          updateTime: '2017-08-11 11:16:43',
          pubTime: '2017-08-11 11:16:43',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,purInteIncome,currSignCustNum,gjTranAmt',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1193,
          name: '历史对比345',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 11:15:53',
          updateTime: '2017-08-11 11:15:53',
          pubTime: '2017-08-11 11:15:53',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,purInteIncome,currSignCustNum',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1190,
          name: '历史1',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 10:33:46',
          updateTime: '2017-08-11 10:33:46',
          pubTime: '2017-08-11 10:33:46',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,currSignCustNum,netIncome,tgNum,signCustPercent',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1189,
          name: '历史对比111',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 10:33:27',
          updateTime: '2017-08-11 10:33:27',
          pubTime: '2017-08-11 10:33:27',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,currSignCustNum,tgNum',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1188,
          name: '历史对比11',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 10:33:00',
          updateTime: '2017-08-11 10:33:00',
          pubTime: '2017-08-11 10:33:00',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,currSignCustNum,tgNum',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1187,
          name: '历史对比1111',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 10:31:43',
          updateTime: '2017-08-11 10:31:43',
          pubTime: '2017-08-11 10:31:43',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,currSignCustNum,tgNum',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1186,
          name: '历史对比看板2222',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 10:30:24',
          updateTime: '2017-08-11 10:30:24',
          pubTime: '2017-08-11 10:30:24',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,currSignCustNum,netIncome,tgNum',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1185,
          name: '历史对比看板77',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 10:16:57',
          updateTime: '2017-08-11 10:16:57',
          pubTime: '2017-08-11 10:16:57',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,currSignCustNum,netIncome',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1184,
          name: '历史对比看板7777',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 10:14:11',
          updateTime: '2017-08-11 10:14:11',
          pubTime: '2017-08-11 10:14:11',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,currSignCustNum,netIncome,prdtTranAmt',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1182,
          name: '历史对比看板888',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 10:10:57',
          updateTime: '2017-08-11 10:10:57',
          pubTime: '2017-08-11 10:10:57',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,purInteIncome,currSignCustNum,prdtTranAmt,gjTranAmt',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1181,
          name: '历史对比看板777',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 10:05:13',
          updateTime: '2017-08-11 10:05:13',
          pubTime: '2017-08-11 10:05:13',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,purInteIncome,currSignCustNum,prdtTranAmt',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1180,
          name: '历史对比看板666',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 10:03:44',
          updateTime: '2017-08-11 10:03:44',
          pubTime: '2017-08-11 10:03:44',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,currSignCustNum,netIncome,prdtTranAmt',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1177,
          name: '历史对比',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 09:27:31',
          updateTime: '2017-08-11 09:27:31',
          pubTime: '2017-08-11 09:27:31',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,purInteIncome,currSignCustNum,netIncome',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1175,
          name: '我的啦wod',
          boardType: 'TYPE_LSDB_JYYJ',
          boardTypeDesc: '经营业绩历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: '用来测试999',
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-11 09:23:48',
          updateTime: '2017-08-11 09:23:48',
          pubTime: '2017-08-11 09:23:48',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'tgInNum',
          custContrastIndicators: 'tgInNum',
          investContrastIndicators: 'tgInNum',
        },
        {
          id: 1158,
          name: '投顾2',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-10 14:19:40',
          updateTime: '2017-08-10 14:19:40',
          pubTime: '2017-08-10 14:19:40',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'newCustInAset,configReportNum,netIncome,tgInNum,currSignCustNum,currSignCustAset,totAset,purRake,purInteIncome',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1154,
          name: '历史对比看板',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-10 10:00:22',
          updateTime: '2017-08-10 10:00:22',
          pubTime: '2017-08-10 10:00:22',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,purInteIncome,currSignCustNum,prdtTranAmt,netIncome',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1153,
          name: '我的看板',
          boardType: 'TYPE_LSDB_JYYJ',
          boardTypeDesc: '经营业绩历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-10 09:32:07',
          updateTime: '2017-08-10 09:32:07',
          pubTime: '2017-08-10 09:32:07',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totCustNum,allTotAset,zhTranAmt,curPrdtTranAmt,allIncomeAmt,effCustNum',
          custContrastIndicators: 'totCustNum,pCustNum,oCustNum,oNewCustNum,oNewPrdtCustNum,InminorCustNum',
          investContrastIndicators: 'totCustNum,pCustNum,oCustNum,oNewCustNum,oNewPrdtCustNum,InminorCustNum',
        },
        {
          id: 1151,
          name: '投顾test',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-09 17:18:08',
          updateTime: '2017-08-09 17:19:17',
          pubTime: '2017-08-09 17:19:17',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'currSignCustAset,gjAvgPercent,purRake,prdtPurFee,currSignCustNum,prdtTranAmt,effSignCustNum',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1131,
          name: '历史对比看板1',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-09 13:49:09',
          updateTime: '2017-08-09 13:49:09',
          pubTime: '2017-08-09 13:49:09',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,purRake,prdtPurFee,purInteIncome,prdtTranAmt,netIncome',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
        {
          id: 1114,
          name: 'test3',
          boardType: 'TYPE_LSDB_JYYJ',
          boardTypeDesc: '经营业绩历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-08 16:41:29',
          updateTime: '2017-08-08 16:41:29',
          pubTime: '2017-08-08 16:41:29',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totCustNum,allTotAset,zhTranAmt,curPrdtTranAmt,allIncomeAmt,nowMktVal',
          custContrastIndicators: 'totCustNum,pCustNum,oCustNum,oNewCustNum,oNewPrdtCustNum,InminorCustNum',
          investContrastIndicators: 'totCustNum,pCustNum,oCustNum,oNewCustNum,oNewPrdtCustNum,InminorCustNum',
        },
        {
          id: 1071,
          name: 'test2',
          boardType: 'TYPE_LSDB_TGJX',
          boardTypeDesc: '投顾绩效历史对比',
          boardStatus: 'RELEASE',
          boardStatusDesc: '发布',
          description: null,
          ownerOrgId: 'ZZ001041',
          createTime: '2017-08-07 16:54:11',
          updateTime: '2017-08-07 16:54:11',
          pubTime: '2017-08-07 16:54:11',
          isEditable: 'Y',
          summuryIndicators: null,
          detailIndicators: null,
          coreIndicators: 'totAset,currSignCustAset,gjAvgPercent,tgNum',
          custContrastIndicators: 'custNum,currSignCustNum',
          investContrastIndicators: 'custNum,currSignCustNum',
        },
      ],
    },
  };
};
